export const coffeeCabanaKeywords = [
  // === ENGLISH KEYWORDS ===
  
  // Brand & Direct
  "coffee cabana",
  "coffee cabana terceira",
  "coffee cabana azores",
  "coffee cabana angra",
  "coffee cabana angra do heroismo",
  "cabana cafe",
  "cabana coffee",
  
  // Core Coffee
  "coffee terceira",
  "coffee azores", 
  "coffee angra",
  "coffee angra do heroismo",
  "terceira coffee shop",
  "azores coffee shop",
  "angra coffee shop",
  "angra do heroismo coffee",
  "best coffee terceira",
  "best coffee angra",
  "specialty coffee azores",
  "organic coffee terceira",
  "fresh coffee azores",
  "local coffee angra",
  "artisan coffee azores",
  
  // Location Specific
  "coffee sao mateus",
  "sao mateus coffee shop",
  "sao mateus da calheta coffee",
  "terceira island coffee",
  "azores islands coffee",
  "coffee near angra do heroismo",
  "coffee shops near angra",
  "angra terceira coffee",
  
  // Breakfast & Food
  "breakfast terceira",
  "breakfast azores",
  "breakfast angra",
  "breakfast angra do heroismo",
  "brunch terceira",
  "brunch azores",
  "brunch angra",
  "breakfast sao mateus",
  "pancakes terceira",
  "pancakes angra",
  "waffles azores",
  "avocado toast terceira",
  "avocado toast angra",
  "chia pudding azores",
  "banana bread terceira",
  "fresh fruit breakfast azores",
  "healthy breakfast terceira",
  "healthy breakfast angra",
  "organic breakfast azores",
  
  // Near Me Searches
  "breakfast near me terceira",
  "coffee near me terceira",
  "coffee near me angra",
  "breakfast near me angra",
  "coffee shop near me azores",
  "breakfast near me azores",
  "cafe near me terceira",
  "cafe near me angra do heroismo",
  "restaurants near angra",
  
  // Plantation & Farm
  "coffee plantation terceira",
  "coffee farm terceira",
  "coffee plantation azores",
  "coffee farm azores",
  "coffee plantation near angra",
  "coffee farm near angra do heroismo",
  "coffee farm tour terceira",
  "plantation tour azores",
  "coffee roasting terceira",
  "coffee tasting terceira",
  "coffee roasting demonstration azores",
  "farm to cup experience terceira",
  "coffee tour from angra",
  
  // Tropical Fruits
  "tropical fruit farm terceira",
  "banana plantation terceira",
  "mango farm azores",
  "avocado farm terceira",
  "papaya plantation azores",
  "tropical fruit tour terceira",
  "organic fruit farm azores",
  "fresh tropical fruit azores",
  "fruit farm near angra",
  
  // Experience & Tourism
  "things to do terceira",
  "things to do angra",
  "things to do angra do heroismo",
  "terceira attractions",
  "angra attractions",
  "azores experiences",
  "terceira farm tours",
  "azores agritourism",
  "coffee experience terceira",
  "unique experiences terceira",
  "terceira hidden gems",
  "authentic terceira experience",
  "local experience terceira",
  "cultural experience azores",
  "day trips from angra",
  "excursions from angra do heroismo",
  
  // Travel & Tourism
  "terceira itinerary",
  "angra itinerary",
  "what to do terceira",
  "what to do angra",
  "best places terceira",
  "best places angra do heroismo",
  "terceira must visit",
  "angra must visit",
  "azores travel guide",
  "terceira food tour",
  "angra food tour",
  "where to eat terceira",
  "where to eat angra",
  "terceira restaurants",
  "angra restaurants",
  "azores dining",
  
  // Distance & Travel from Angra
  "coffee plantation 15 minutes from angra",
  "farm tour near angra do heroismo",
  "day trip from angra terceira",
  "drive from angra to coffee farm",
  "activities outside angra",
  "countryside near angra",
  
  // Long-tail Specific
  "organic coffee plantation tour terceira",
  "best avocado toast azores",
  "fresh banana bread terceira island",
  "coffee roasting demonstration azores",
  "sustainable coffee farm terceira",
  "tropical fruit breakfast terceira",
  "family friendly coffee farm azores",
  "instagrammable coffee shop terceira",
  "farm to table breakfast terceira",
  "ethical coffee sourcing azores",
  "coffee farm tour from angra do heroismo",
  "organic breakfast near angra",
  
  // Voice Search
  "where can i get good coffee in terceira",
  "best breakfast in terceira azores",
  "coffee plantation tours near terceira",
  "where to see coffee being made terceira",
  "organic coffee shop terceira azores",
  "coffee farm near angra do heroismo",
  "breakfast places driving distance from angra",
  
  // Problem Solving
  "where to get real coffee terceira",
  "healthy breakfast options terceira",
  "fresh roasted coffee azores",
  "sustainable tourism terceira",
  "eco friendly coffee terceira",
  "authentic local experience near angra",
  
  // === PORTUGUESE KEYWORDS ===
  
  // Marca & Direto
  "café cabana",
  "coffee cabana terceira",
  "café cabana terceira",
  "café cabana angra",
  "café cabana angra do heroísmo",
  "cabana café",
  "café da cabana",
  
  // Café Principal
  "café terceira",
  "café açores",
  "café angra",
  "café angra do heroísmo",
  "café são mateus",
  "café são mateus da calheta",
  "melhor café terceira",
  "melhor café angra",
  "café especial açores",
  "café orgânico terceira",
  "café biológico açores",
  "café fresco terceira",
  "café local açores",
  "café artesanal terceira",
  "cafetaria angra",
  "cafetaria angra do heroísmo",
  
  // Localização Específica
  "café são mateus da calheta",
  "cafetaria são mateus",
  "café ilha terceira",
  "café ilhas açores",
  "café calheta terceira",
  "café perto angra",
  "café perto angra do heroísmo",
  "cafetarias angra terceira",
  
  // Pequeno-almoço & Comida
  "pequeno almoço terceira",
  "pequeno almoço açores",
  "pequeno almoço angra",
  "pequeno almoço angra do heroísmo",
  "café da manhã terceira",
  "café da manhã açores",
  "café da manhã angra",
  "brunch terceira",
  "brunch açores",
  "brunch angra",
  "pequeno almoço são mateus",
  "panquecas terceira",
  "panquecas angra",
  "waffles açores",
  "torrada abacate terceira",
  "torrada abacate angra",
  "pudim chia açores",
  "pão banana terceira",
  "fruta fresca açores",
  "pequeno almoço saudável terceira",
  "pequeno almoço saudável angra",
  "pequeno almoço orgânico açores",
  
  // Pesquisas "Perto de Mim"
  "café perto de mim terceira",
  "café perto de mim angra",
  "pequeno almoço perto de mim terceira",
  "pequeno almoço perto de mim angra",
  "cafetaria perto de mim açores",
  "restaurante perto de mim são mateus",
  "café perto terceira",
  "café perto angra do heroísmo",
  "restaurantes perto angra",
  
  // Plantação & Quinta
  "plantação café terceira",
  "quinta café terceira",
  "plantation café açores",
  "quinta café açores",
  "plantação café perto angra",
  "quinta café perto angra do heroísmo",
  "visita quinta café terceira",
  "tour plantação açores",
  "torra café terceira",
  "degustação café terceira",
  "demonstração torra café açores",
  "experiência quinta mesa terceira",
  "tour café desde angra",
  "visita quinta desde angra do heroísmo",
  
  // Frutas Tropicais
  "quinta frutas tropicais terceira",
  "plantação banana terceira",
  "quinta manga açores",
  "plantação abacate terceira",
  "quinta papaia açores",
  "tour frutas tropicais terceira",
  "quinta frutas biológicas açores",
  "frutas tropicais frescas açores",
  "quinta frutas perto angra",
  
  // Experiência & Turismo
  "o que fazer terceira",
  "o que fazer angra",
  "o que fazer angra do heroísmo",
  "atrações terceira",
  "atrações angra",
  "experiências açores",
  "tours quinta terceira",
  "agriturismo açores",
  "experiência café terceira",
  "experiências únicas terceira",
  "tesouros escondidos terceira",
  "experiência autêntica terceira",
  "experiência local terceira",
  "experiência cultural açores",
  "passeios desde angra",
  "excursões angra do heroísmo",
  
  // Viagem & Turismo
  "roteiro terceira",
  "roteiro angra",
  "o que visitar terceira",
  "o que visitar angra",
  "melhores locais terceira",
  "melhores locais angra do heroísmo",
  "terceira obrigatório visitar",
  "angra obrigatório visitar",
  "guia viagem açores",
  "tour gastronómico terceira",
  "tour gastronómico angra",
  "onde comer terceira",
  "onde comer angra",
  "restaurantes terceira",
  "restaurantes angra",
  "gastronomia açores",
  
  // Distância & Viagem desde Angra
  "plantação café 15 minutos angra",
  "tour quinta perto angra do heroísmo",
  "passeio dia desde angra terceira",
  "conduzir angra quinta café",
  "atividades fora angra",
  "campo perto angra",
  
  // Específico Longo
  "tour quinta café orgânico terceira",
  "melhor torrada abacate açores",
  "pão banana fresco ilha terceira",
  "demonstração torra café açores",
  "quinta café sustentável terceira",
  "pequeno almoço frutas tropicais terceira",
  "quinta café família açores",
  "cafetaria instagram terceira",
  "pequeno almoço quinta mesa terceira",
  "café origem ética açores",
  "tour quinta café desde angra do heroísmo",
  "pequeno almoço orgânico perto angra",
  
  // Pesquisa Voz
  "onde posso beber bom café terceira",
  "melhor pequeno almoço terceira açores",
  "tours plantação café perto terceira",
  "onde ver produção café terceira",
  "cafetaria orgânica terceira açores",
  "quinta café perto angra do heroísmo",
  "locais pequeno almoço conduzir angra",
  
  // Resolução Problemas
  "onde beber café verdadeiro terceira",
  "opções pequeno almoço saudável terceira",
  "café torrado fresco açores",
  "turismo sustentável terceira",
  "café ecológico terceira",
  "experiência local autêntica perto angra",
  
  // Regionalismos Açorianos
  "café açoriano tradicional",
  "pequeno almoço açoriano",
  "produtos locais terceira",
  "quinta agriturismo açores",
  "café produção local terceira",
  "agricultura biológica açores",
  "turismo rural terceira",
  "experiência açoriana autêntica",
  "café típico angra do heroísmo"
]